# Generated by Django 5.1 on 2024-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('ranking', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='city/images/')),
            ],
        ),
    ]
