# Generated by Django 5.0.7 on 2024-08-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='ranking',
        ),
    ]
