# Generated by Django 5.0.7 on 2024-08-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('general_review', models.CharField(max_length=2000)),
                ('touristic_places_rate', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eigth'), (9, 'Nine'), (10, 'Ten')], default=1)),
                ('history_and_culture_rate', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eigth'), (9, 'Nine'), (10, 'Ten')], default=1)),
                ('gastronomy_rate', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eigth'), (9, 'Nine'), (10, 'Ten')], default=1)),
                ('costs_rate', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eigth'), (9, 'Nine'), (10, 'Ten')], default=1)),
                ('safety_rate', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eigth'), (9, 'Nine'), (10, 'Ten')], default=1)),
                ('weather_rate', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eigth'), (9, 'Nine'), (10, 'Ten')], default=1)),
                ('general_rate', models.FloatField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
